name: Cancel long-queued jobs

on:
  schedule:
    # Every 4 hours
    - cron: "17 */4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: torchci
jobs:
  cancel-queued-jobs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: yarn install --frozen-lockfile
      - run: yarn node scripts/cancelQueuedJobs.mjs
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HUD_API_TOKEN: ${{ secrets.HUD_API_TOKEN }}
