name: Lambda Runners
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-runners.yml
      - "terraform-aws-github-runner/modules/runners/lambdas/runners/**"

jobs:
  build:
    name: "Run tests for runners lambda"
    runs-on: ubuntu-latest
    container: node:20
    defaults:
      run:
        working-directory: terraform-aws-github-runner/modules/runners/lambdas/runners

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build, Lint, and Test
        run: make build
